### ISSUE TITLE
why specific version of multicolumnwizard?

### ISSUE THREAD

**Issue by fritzmg** [Kuestenschmiede/con4gis_core#28]
The [`composer.json`](https://github.com/Kuestenschmiede/con4gis_core/blob/v1.7.1/composer.json#L18) requires
```
"menatwork/contao-multicolumnwizard": "3.3.8"
```
Why do you require a specific version? This seems unnecessarily restricting.

**Comment by coastforge-mei** [comment]
We changed this composer.json entry to: ^3.3.6. Thank for you response.

**Comment by amenk** [comment]
Thank you - can you tag a relase?

**Comment by amenk** [comment]
Also packagist does not seem to be updated with the latest dev-develop version?
