### ISSUE TITLE
Incompatibility with Contao 3.5 due to wrong version checking

### ISSUE THREAD

**Issue by KaiserCh** [Kuestenschmiede/con4gis_core#29]
In at least 2 files, the version checking should be switched, otherwise the extension will not work correctly in Contao 3.5:
https://github.com/Kuestenschmiede/con4gis_core/blob/master/config/config.php#L45
https://github.com/Kuestenschmiede/con4gis_core/blob/master/templates/be_c4g_info.html5#L35

If you first check for class_exists, PHP will resolve the whole class, including its parents. This will fail in Contao 3.5 with "PHP Fatal error:  Class 'Contao\CoreBundle\Controller\FrontendController' not found". If you first call the version_compare() statement instead, the class_exists() won't need to fire in Contao 3.5.
This will not only solve the issue but will also speed anything up a tiny bit by not loading unnecessary files.

`if ((version_compare( VERSION, '4', '>=' )) && class_exists('\con4gis\ApiBundle\Controller\ApiController'))` 

Also, as con4gis_core depends on con4gis_api_bundle, the class_exists()-statement is unnecessary itself. The class should always exist (but will not resolve correctly in Contao <4), unless someone messed up the installer. In that case, it would crash once the API needs to be loaded (Contao >= 4) either way.

**Comment by coastforge-mei** [comment]
we applied your suggestion: https://github.com/Kuestenschmiede/con4gis_core/commit/47aa468f9453cc7aa4bba60329725afb2c021a8e
